# Site settings
name: Idris Abdul-Lateef
title: Idris Abdul-Lateef | Front-End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://eedris.dev/
baseurl: ''
email: alabialade@gmail.com
cover: https://eedris.dev/img/og.png
logo: https://eedris.dev/img/emojis/technologist.png
resume: https://eedris.dev/resume.pdf
social:
  - title: email
    url: mailto:alabialade@gmail.com
  - title: twitter
    url: https://twitter.com/eedrxs
  - title: github
    url: https://github.com/eedrxs
  - title: linkedin
    url: https://www.linkedin.com/in/eedris
  - title: blog
    url: https://blog.eedris.dev/
  # - title: instagram
  #   url: https://instagram.com/eedrxs

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
